version: "3.9"
services:
  frontend:
    build: ui
    ports: 
      - 3000:3000
    links:
      - backend
    container_name: frontend
  backend:
    build: core/transport
    ports:
      - 8080:8080
    links:
      - redis
    container_name: backend
  redis:
    container_name: redis
    image: redis:6.0
    ports:
      - 6379:6379
